"""add exclude_from_stats to refuel_entries

Revision ID: 0b35e5ca0b45
Revises: 257bf9a1d963
Create Date: 2026-06-01 00:03:04.435762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b35e5ca0b45'
down_revision: Union[str, Sequence[str], None] = '257bf9a1d963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refuel_entries', sa.Column('exclude_from_stats', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refuel_entries', 'exclude_from_stats')
    # ### end Alembic commands ###
