"""add indexes for performance

Revision ID: 0db817fe5752
Revises: c2d4e6f8a0b2
Create Date: 2026-06-11 18:27:44.182135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db817fe5752'
down_revision: Union[str, Sequence[str], None] = 'c2d4e6f8a0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pilot_refuels_vehicle_date', 'pilot_refuels', ['vehicle_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_refuel_entries_pilot_refuel_id'), 'refuel_entries', ['pilot_refuel_id'], unique=False)
    op.create_index('ix_refuel_entries_vehicle_date', 'refuel_entries', ['vehicle_id', 'event_date'], unique=False)
    op.create_index('ix_trip_summaries_vehicle_date', 'trip_summaries', ['vehicle_id', 'date'], unique=False)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_index(op.f('ix_vehicles_site_id'), 'vehicles', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_site_id'), table_name='vehicles')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index('ix_trip_summaries_vehicle_date', table_name='trip_summaries')
    op.drop_index('ix_refuel_entries_vehicle_date', table_name='refuel_entries')
    op.drop_index(op.f('ix_refuel_entries_pilot_refuel_id'), table_name='refuel_entries')
    op.drop_index('ix_pilot_refuels_vehicle_date', table_name='pilot_refuels')
    # ### end Alembic commands ###
