"""add pilot_password to users

Revision ID: 15879b667715
Revises: 3635d85295d2
Create Date: 2026-05-31 22:09:51.764086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15879b667715'
down_revision: Union[str, Sequence[str], None] = '3635d85295d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pilot_password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pilot_password')
    # ### end Alembic commands ###
