"""add vehicle threshold columns

Revision ID: 257bf9a1d963
Revises: 4800d06a5875
Create Date: 2026-05-31 23:30:54.111101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257bf9a1d963'
down_revision: Union[str, Sequence[str], None] = '4800d06a5875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('enable_abs_threshold', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('vehicles', sa.Column('normal_threshold_pct', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('warning_threshold_pct', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('normal_threshold_abs', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('warning_threshold_abs', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'warning_threshold_abs')
    op.drop_column('vehicles', 'normal_threshold_abs')
    op.drop_column('vehicles', 'warning_threshold_pct')
    op.drop_column('vehicles', 'normal_threshold_pct')
    op.drop_column('vehicles', 'enable_abs_threshold')
    # ### end Alembic commands ###
