"""initial

Revision ID: 3c51c85d78a6
Revises: 
Create Date: 2026-05-28 00:37:15.499030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c51c85d78a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('pilot_token', sa.Text(), nullable=True),
    sa.Column('pilot_node_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_agent_id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('folder', sa.String(length=200), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_pilot_agent_id'), 'vehicles', ['pilot_agent_id'], unique=True)
    op.create_table('fuel_sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('pilot_sensor_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_sensors_vehicle_id'), 'fuel_sensors', ['vehicle_id'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('sync_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_affected', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_refuels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('start_level', sa.Float(), nullable=True),
    sa.Column('end_level', sa.Float(), nullable=True),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['fuel_sensors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_refuels_event_date'), 'pilot_refuels', ['event_date'], unique=False)
    op.create_index(op.f('ix_pilot_refuels_vehicle_id'), 'pilot_refuels', ['vehicle_id'], unique=False)
    op.create_table('refuel_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('pilot_refuel_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('pilot_amount', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('difference', sa.Float(), nullable=True),
    sa.Column('error_percent', sa.Float(), nullable=True),
    sa.Column('comparison_status', sa.String(length=30), nullable=True),
    sa.Column('is_false', sa.Boolean(), nullable=False),
    sa.Column('false_reason', sa.Text(), nullable=True),
    sa.Column('false_marked_by', sa.String(length=100), nullable=True),
    sa.Column('false_marked_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pilot_refuel_id'], ['pilot_refuels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refuel_entries_event_date'), 'refuel_entries', ['event_date'], unique=False)
    op.create_index(op.f('ix_refuel_entries_vehicle_id'), 'refuel_entries', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refuel_entries_vehicle_id'), table_name='refuel_entries')
    op.drop_index(op.f('ix_refuel_entries_event_date'), table_name='refuel_entries')
    op.drop_table('refuel_entries')
    op.drop_index(op.f('ix_pilot_refuels_vehicle_id'), table_name='pilot_refuels')
    op.drop_index(op.f('ix_pilot_refuels_event_date'), table_name='pilot_refuels')
    op.drop_table('pilot_refuels')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_fuel_sensors_vehicle_id'), table_name='fuel_sensors')
    op.drop_table('fuel_sensors')
    op.drop_index(op.f('ix_vehicles_pilot_agent_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
