"""add details_json to sync_log

Revision ID: 4800d06a5875
Revises: 15879b667715
Create Date: 2026-05-31 22:27:20.446081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4800d06a5875'
down_revision: Union[str, Sequence[str], None] = '15879b667715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_log', sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_log', 'details_json')
    # ### end Alembic commands ###
