"""add_sensor_status_to_vehicles

Revision ID: 4845cc480b83
Revises: b618705b2cf5
Create Date: 2026-05-29 00:56:49.247927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4845cc480b83'
down_revision: Union[str, Sequence[str], None] = 'b618705b2cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('sensor_status', sa.String(length=20), server_default='normal', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'sensor_status')
    # ### end Alembic commands ###
