"""add has_fuel_sensor to vehicles

Revision ID: 58b9bcc1c61f
Revises: b2247253d779
Create Date: 2026-05-28 01:15:11.018837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b9bcc1c61f'
down_revision: Union[str, Sequence[str], None] = 'b2247253d779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('has_fuel_sensor', sa.Boolean(), server_default='t', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'has_fuel_sensor')
    # ### end Alembic commands ###
