"""add owner location sensor_count to vehicles

Revision ID: b2247253d779
Revises: 143d33335d90
Create Date: 2026-05-28 01:06:11.796492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2247253d779'
down_revision: Union[str, Sequence[str], None] = '143d33335d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('owner', sa.String(length=200), nullable=True))
    op.add_column('vehicles', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('vehicles', sa.Column('sensor_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('vehicles', 'sensor_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'sensor_count')
    op.drop_column('vehicles', 'location')
    op.drop_column('vehicles', 'owner')
    # ### end Alembic commands ###
