"""add created_by to refuel_entries

Revision ID: b618705b2cf5
Revises: a5f49c42ab1a
Create Date: 2026-05-28 22:33:03.777606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b618705b2cf5'
down_revision: Union[str, Sequence[str], None] = 'a5f49c42ab1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refuel_entries', sa.Column('created_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refuel_entries', 'created_by')
    # ### end Alembic commands ###
