"""add icon_style to vehicles

Revision ID: ec57a2531e4b
Revises: 09e47dc17a1d
Create Date: 2026-06-03 12:30:15.545582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec57a2531e4b'
down_revision: Union[str, Sequence[str], None] = '09e47dc17a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('icon_style', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'icon_style')
    # ### end Alembic commands ###
